prog:menu.o main.o
	gcc menu.o main.o -o prog -lSDL -lSDL_image  -lSDL_mixer -lSDL_ttf -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image  -lSDL_mixer -lSDL_ttf -g 
menu.o:menu.c
	gcc -c menu.c -lSDL -lSDL_image  -lSDL_mixer -lSDL_ttf -g
